sudo: required
services:
  - docker

before_install:
  - docker build -t reric84/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true reric84/react-test npm test

after_success:
  - docker build -t reric84/multi-client ./client
  - docker build -t reric84/multi-nginx ./nginx
  - docker build -t reric84/multi-server ./server
  - docker build -t reric84/multi-worker ./worker
# Log in to the docker CLI
  - echo "$DCOKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Take those images and push them to docker hub
  - docker push reric84/multi-client
    docker push reric84/multi-nginx
    docker push reric84/multi-server
    docker push reric84/multi-worker